"use client";

import { Sparkles, Lock } from "lucide-react";
import type { HealthMetrics } from "@/lib/finance";
import { formatCurrency } from "@/lib/format";

/**
 * Placeholder for the "co-piloto" daily tip. Right now it derives a simple,
 * rule-based message locally. Later this will be replaced by a message
 * generated by Claude (Anthropic API) delivered every day at 9am.
 */
export function DailyTipCard({
  health,
  hasData,
  currency,
}: {
  health: HealthMetrics;
  hasData: boolean;
  currency: string;
}) {
  const tip = buildLocalTip(health, hasData, currency);

  return (
    <div className="relative overflow-hidden rounded-[var(--radius-lg)] border border-border bg-gradient-to-br from-primary-soft to-surface p-5">
      <div className="flex items-start gap-3">
        <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm">
          <Sparkles className="size-5" />
        </div>
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <p className="text-sm font-semibold text-foreground">
              Dica do dia
            </p>
            <span className="inline-flex items-center gap-1 rounded-full bg-surface-2 px-2 py-0.5 text-[10px] font-medium text-muted">
              <Lock className="size-3" /> IA em breve
            </span>
          </div>
          <p className="mt-1 text-sm leading-relaxed text-foreground/90">
            {tip}
          </p>
          <p className="mt-2 text-xs text-muted">
            Todo dia às 9h o Claude vai entregar aqui um incentivo ou um alerta
            no tom certo. (Ativaremos quando adicionar créditos na API.)
          </p>
        </div>
      </div>
    </div>
  );
}

function buildLocalTip(
  health: HealthMetrics,
  hasData: boolean,
  currency: string,
): string {
  if (!hasData) {
    return "Comece registrando suas entradas e custos fixos para eu calcular sua base do mês.";
  }
  if (health.available <= 0) {
    return "Melhor segurar a mão hoje — o disponível do mês já está no limite. 🛑";
  }
  const perDay = formatCurrency(Math.max(0, health.dailyAllowance), currency);
  return `Você tem ${formatCurrency(
    health.available,
    currency,
  )} livres para o resto do mês — cerca de ${perDay} por dia. Dá pra aproveitar sem culpa. ✨`;
}
